export {
  useCreateCommentMutation,
  useUploadImagesMutation,
  useCreatePostMutation,
  useGetCommentRepliesInfiniteQuery,
  useGetFeedPostsInfiniteQuery,
  useGetPostCommentsInfiniteQuery,
  useGetUserPostsInfiniteQuery,
  useReplyToCommentMutation,
  useToggleCommentLikeMutation,
} from './api/post.api'
export { fetchPost, fetchUserPosts } from './api/post.server'
export type {
  CommentAuthor,
  CreatedCommentResponse,
  CreateCommentRequest,
  CreatePostRequest,
  CreatePostResponse,
  DeleteUserPost,
  GetCommentRepliesArgs,
  GetPostCommentsArgs,
  GetUserPostsArgs,
  Image,
  Post,
  PostComment,
  ReplyToCommentRequest,
  ResponseGetFeedPosts,
  ResponseGetPostComments,
  UpdateUserPost,
  ToggleCommentLikeRequest,
  UploadImagesResponseType,
} from './api/post.types'
